multi host support

diff --git a/comploy b/comploy
--- a/comploy
+++ b/comploy
@@ -11,11 +11,9 @@
 #add files to not deploy here, seperate with a space
 ignored_files="comploy composer.lock composer.json session.vim .env .git* *database.sqlite storage/*"
 
-#destination server and domain
+#destination host domain/IP address.
+#you can add multiple servers, seperated by a space
 host=""
-
-#the dir to contain your public files on the server
-server_dir="/var/www/$host"
 
 
 #################################################################
@@ -27,14 +25,17 @@ server_dir="/var/www/$host"
 #                /____/       
 #################################################################
 
-#detect if we already have deployed by checking if the folder's empty
-is_first_run=$(ssh root@$host 'if [ -z "$(ls -A '$server_dir')" ];then echo 1;fi;')
+for host in $hosts; do
+    server_dir="/var/www/$host"
+    #detect if we already have deployed by checking if the folder's empty
+    is_first_run=$(ssh root@$host 'if [ -z "$(ls -A '$server_dir')" ];then echo 1;fi;')
 
-# if there are uncommitted shit on first run
-if ( [[ $is_first_run ]] && ( [[ $(git ls-files -m) ]] || [[ $(git ls-files . --exclude-standard --others) ]] ));then
-    echo "ABORTING: Please deploy a working, fresh repository with NO modified - or untracked files."
-    exit 1
-fi
+    # if there are uncommitted shit on first run
+    if ( [[ $is_first_run ]] && ( [[ $(git ls-files -m) ]] || [[ $(git ls-files . --exclude-standard --others) ]] ));then
+        echo "ABORTING: Make sure that your first deploy is from a fresh repository with NO modified - OR untracked files."
+        exit 1
+    fi
+done
 
 #if you provide comploy with an argument (string), use it as commit message if there's staged files. otherwise, simply deploy all unchanged files (since last commit)
 if [[ $(git diff --cached --exit-code) ]] && [ ! -z "$1" -a "$1" != " " ];then
@@ -48,14 +49,18 @@ git ls-files -m >> .ignore
 #add the untracked files to the deploy blacklist
 git ls-files . --exclude-standard --others >> .ignore
 
-echo "Syncing files..."
 #sync the files
-rsync -a --delete --exclude-from ".ignore" ./ root@$host:$server_dir
+for host in $hosts; do
+    server_dir="/var/www/$host"
+    echo "Syncing with $host..."
+    rsync -a --delete --exclude-from ".ignore" ./ root@$host:$server_dir
+
+    #set the correct folder permissions
+    ssh root@$host "chown -R www-data:www-data /var/www/*;chmod -R 755 /var/www;"
+done
+
 #remove the temporary, aggregated ignore list
 rm -f .ignore
-
-#set the correct folder permissions
-ssh root@$host "chown -R www-data:www-data /var/www/*;chmod -R 755 /var/www;"
 
 #all is well
 echo "Project synced and ready to go!"
